project: "clash-lang/clash-shockwaves"
title_format: "## v{version} - *{date}*"
md_pr_link: "[!{pr}]({pr_url})"
default_cats:
  HIGHLIGHT:
    title: "Highlights"
    rank: -1
    itemize: false
    notitle: true
  UPKEEP:
    title: "Upkeep"
    rank: 1
    itemize: true
    notitle: false
  ADDED:
    title: "Added"
    rank: 2
    itemize: true
    notitle: false
  CHANGED:
    title: "Changed"
    rank: 3
    itemize: true
    notitle: false
  FIXED:
    title: "Fixed"
    rank: 4
    itemize: true
    notitle: false
  DEPRECATED:
    title: "Deprecated"
    rank: 5
    itemize: true
    notitle: false
  REMOVED:
    title: "Removed"
    rank: 6
    itemize: true
    notitle: false
  PERFORMANCE:
    title: "Performance"
    rank: 7
    itemize: true
    notitle: false
